# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=2000)),
                ('processor', models.CharField(max_length=2000)),
                ('ram', models.CharField(max_length=100)),
                ('hdd', models.CharField(max_length=250)),
                ('display_size', models.CharField(max_length=250)),
                ('warranty', models.CharField(max_length=1000)),
                ('slug_name', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptops',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=2000)),
                ('box_contains', models.CharField(default='NA', max_length=5000)),
                ('ram', models.CharField(default='NA', max_length=100)),
                ('storage', models.CharField(default='NA', max_length=250)),
                ('model_number', models.CharField(default='NA', max_length=250)),
                ('model_name', models.CharField(default='NA', max_length=250)),
                ('color', models.CharField(default='NA', max_length=250)),
                ('display_size', models.CharField(default='NA', max_length=250)),
                ('processor', models.CharField(default='NA', max_length=250)),
                ('primary_camera', models.CharField(default='NA', max_length=250)),
                ('secondary_camera', models.CharField(default='NA', max_length=250)),
                ('battery', models.CharField(default='NA', max_length=250)),
                ('sensors', models.CharField(default='NA', max_length=1000)),
                ('warranty', models.CharField(default='NA', max_length=250)),
                ('slug_name', models.SlugField(default='NA', unique=True)),
            ],
            options={
                'verbose_name': 'Mobile',
                'verbose_name_plural': 'Mobiles',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=2000, unique=True)),
                ('image_src', models.CharField(max_length=2500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('type', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='mobile',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompany.ProductTypes'),
        ),
        migrations.AddField(
            model_name='laptops',
            name='type',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='kompany.ProductTypes'),
        ),
    ]
