# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=2000)),
                ('processor', models.CharField(max_length=2000)),
                ('ram', models.CharField(max_length=100)),
                ('hdd', models.CharField(max_length=250)),
                ('display_size', models.CharField(max_length=250)),
                ('warranty', models.CharField(max_length=1000)),
                ('slug_name', models.SlugField(unique=True)),
            ],
        ),
    ]
