# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'ProductImage', 'verbose_name_plural': 'ProductImages'},
        ),
        migrations.AlterModelOptions(
            name='producttypes',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.AlterField(
            model_name='mobile',
            name='slug_name',
            field=models.SlugField(unique=True),
        ),
    ]
