# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0002_auto_20171012_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kompany.ProductTypes'),
        ),
    ]
