# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0002_laptops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptops',
            options={'verbose_name': 'Laptop', 'verbose_name_plural': 'Laptops'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
