# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0004_auto_20171012_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='battery',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='box_contains',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='color',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='display_size',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='model_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='model_number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='primary_camera',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='processor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='secondary_camera',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='sensors',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='storage',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='warranty',
            field=models.CharField(max_length=250),
        ),
    ]
