# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 16:16
from __future__ import unicode_literals

from django.utils.text import slugify
from django.db import migrations


class Migration(migrations.Migration):
    def slugify_title(apps, schema_editor):
        Post = apps.get_model('kompany', 'Mobile')
        for post in Post.objects.all():
            post.slug = slugify(post.product_name)
            post.save()

    dependencies = [
        ('kompany', '0005_auto_20171012_2128'),
    ]

    operations = [
        migrations.RunPython(slugify_title),
    ]
