# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0006_auto_20171012_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image_src',
            field=models.CharField(max_length=2500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product_id',
            field=models.CharField(max_length=2000),
        ),
    ]
