# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0007_auto_20171012_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_name', models.CharField(max_length=500)),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_images', models.CharField(max_length=10000)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompany.ProductTypes')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='display_size',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='hdd',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='warranty',
        ),
        migrations.AddField(
            model_name='laptops',
            name='price',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
