# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0009_auto_20171019_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='slug_name',
            field=models.SlugField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='slug_name',
            field=models.SlugField(max_length=2000, null=True, unique=True),
        ),
    ]
